"use strict";

import { expect } from "chai";
require("mocha").describe;
require("mocha").it;
import { Parser } from "../../../../src/managers/stackTraceParsers/goStackTraceParser";

describe("goStackTraceParser", () => {
	describe("golang", () => {
		it("console app macOS", () => {
			const str = `goagent.(*txn).WriteHeader (/work/src/github.com/foobar/msmith/vendor/github.com/newrelic/goagent/internal_txn.go:202)
			goagent.wrapCFH.WriteHeader (<autogenerated>:445)
			stats.(*recorderResponseWriter).WriteHeader (/work/src/github.com/foobar/msmith/vendor/github.com/abc/stats/recorder.go:38)
			middlewares.(*responseRecorder).WriteHeader (/work/src/github.com/foobar/msmith/middlewares/stats.go:56)
			foooo.(*responseWriter).WriteHeader (/work/src/github.com/foobar/msmith/vendor/github.com/something/foooo/response_writer.go:53)
			middlewares.(*Retry).ServeHTTP (/work/src/github.com/foobar/msmith/middlewares/retry.go:64)
			foooo.Wrap.func1 (/work/src/github.com/foobar/msmith/vendor/github.com/something/foooo/foooo.go:41)
			foooo.HandlerFunc.ServeHTTP (/work/src/github.com/foobar/msmith/vendor/github.com/something/foooo/foooo.go:24)
			foooo.middleware.ServeHTTP (/work/src/github.com/foobar/msmith/vendor/github.com/something/foooo/foooo.go:33)`;

			const result = Parser(str);
			expect(result).to.deep.equals({
				lines: [
					{
						arguments: undefined,
						column: undefined,
						fileFullPath:
							"/work/src/github.com/foobar/msmith/vendor/github.com/newrelic/goagent/internal_txn.go",
						line: 202,
						method: "goagent.(*txn).WriteHeader"
					},
					{
						arguments: undefined,
						column: undefined,
						fileFullPath: "<autogenerated>",
						line: 445,
						method: "goagent.wrapCFH.WriteHeader"
					},
					{
						arguments: undefined,
						column: undefined,
						fileFullPath:
							"/work/src/github.com/foobar/msmith/vendor/github.com/abc/stats/recorder.go",
						line: 38,
						method: "stats.(*recorderResponseWriter).WriteHeader"
					},
					{
						arguments: undefined,
						column: undefined,
						fileFullPath: "/work/src/github.com/foobar/msmith/middlewares/stats.go",
						line: 56,
						method: "middlewares.(*responseRecorder).WriteHeader"
					},
					{
						arguments: undefined,
						column: undefined,
						fileFullPath:
							"/work/src/github.com/foobar/msmith/vendor/github.com/something/foooo/response_writer.go",
						line: 53,
						method: "foooo.(*responseWriter).WriteHeader"
					},
					{
						arguments: undefined,
						column: undefined,
						fileFullPath: "/work/src/github.com/foobar/msmith/middlewares/retry.go",
						line: 64,
						method: "middlewares.(*Retry).ServeHTTP"
					},
					{
						arguments: undefined,
						column: undefined,
						fileFullPath:
							"/work/src/github.com/foobar/msmith/vendor/github.com/something/foooo/foooo.go",
						line: 41,
						method: "foooo.Wrap.func1"
					},
					{
						arguments: undefined,
						column: undefined,
						fileFullPath:
							"/work/src/github.com/foobar/msmith/vendor/github.com/something/foooo/foooo.go",
						line: 24,
						method: "foooo.HandlerFunc.ServeHTTP"
					},
					{
						arguments: undefined,
						column: undefined,
						fileFullPath:
							"/work/src/github.com/foobar/msmith/vendor/github.com/something/foooo/foooo.go",
						line: 33,
						method: "foooo.middleware.ServeHTTP"
					}
				],
				text: str
			});
		});
	});
});
